In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1,my_list2]

In [7]:
my_array2 = np.array(my_lists)

In [8]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

This is a multi-dimentional array, called a matrix.

Lets see its shape:

In [9]:
my_array2.shape

(2, 4)

This is a 2 x 4. 

Lets see its datatype:

In [10]:
my_array2.dtype

dtype('int64')

Array of all zeros:

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array.dtype

dtype('float64')

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])