In [7]:
import numpy as np

In [4]:
5/2

2.5

In [10]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [11]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [12]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [13]:
# Obvious method to multiple two arrays.

In [14]:
arr2 = np.array([[3,5,7,9],[1,1,2,3]])

In [15]:
arr2

array([[3, 5, 7, 9],
       [1, 1, 2, 3]])

In [16]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [18]:
arr2 ** 3
# Exponential operation

array([[ 27, 125, 343, 729],
       [  1,   1,   8,  27]])