In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Take square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
# Take exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
# Create a random array.
arr_ran_A = np.random.randn(10)
arr_ran_A

array([ 0.39043372,  1.69555942,  1.20040256,  3.27307453, -1.00471515,
        0.31768399, -0.63238672,  1.13058447, -1.01684708,  0.09000418])

In [9]:
arr_ran_B = np.random.randn(10)
arr_ran_B

array([ 0.49684805, -1.25156589,  0.3854366 ,  0.74386157, -0.1573196 ,
        0.25491472, -0.36322684, -1.23889585, -0.63401984,  0.42993419])

In [10]:
# Binary Functions: functions that use two arrays.

In [12]:
# Adds arrays.
np.add(arr_ran_A,arr_ran_B)

array([ 0.88728177,  0.44399353,  1.58583915,  4.0169361 , -1.16203475,
        0.57259872, -0.99561356, -0.10831138, -1.65086693,  0.51993837])

In [13]:
# Finds the maximum difference between two arrays and sets the difference as the value.
np.maximum(arr_ran_A,arr_ran_B)

array([ 0.49684805,  1.69555942,  1.20040256,  3.27307453, -0.1573196 ,
        0.31768399, -0.36322684,  1.13058447, -0.63401984,  0.42993419])

In [15]:
# Finds the minimum difference between two arrays and sets the difference as the value.
np.minimum(arr_ran_A,arr_ran_B)

array([ 0.39043372, -1.25156589,  0.3854366 ,  0.74386157, -1.00471515,
        0.25491472, -0.63238672, -1.23889585, -1.01684708,  0.09000418])