In [3]:
import numpy as np

In [8]:
arr1 = np.arange(0,11)
arr1
# Created array and then ran it to show contents.
# Index starts at 0, so calling it to 11 means 0 - 10.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# If I want to get a value at an index, I can call it at index[#]
arr1[8]

8

In [13]:
# Gets a range.
arr1[1:5]

array([1, 2, 3, 4])

In [14]:
# Get values in a range
arr1[0:5]

array([0, 1, 2, 3, 4])

In [16]:
# Set values in a range to a set value:
arr1[0:5] = 100
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
# Reset the array.
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Slices of an array.
slice_of_arr1 = arr1[0:6]
slice_of_arr1

array([0, 1, 2, 3, 4, 5])

In [26]:
slice_of_arr1[:] = 99
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

In [28]:
# Changes are also made to the original array as well.
# Slices of the original array are part of original array.
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
# To explicitly make a copy of part of an array instead
arr1_copy = arr1.copy()
arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array(([5,10,15,20],[25,30,35,40],[45,50,55,60]))
arr_2d

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [31]:
# Index array. Index starts at '0'.
arr_2d[1]

array([25, 30, 35, 40])

In [34]:
# Individual element value
# index[row#][column#]
arr_2d[1][0]

25

In [35]:
arr_2d[:2,1:]

array([[10, 15, 20],
       [30, 35, 40]])

In [36]:
arr_2d[:3,2:]

array([[15, 20],
       [35, 40],
       [55, 60]])

In [38]:
# Fancy indexing
arr_2d_2 = np.zeros((10,10))
arr_2d_2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
arr_length = arr_2d_2.shape[1]

In [40]:
arr_length

10

In [46]:
for i in range(arr_length):
    arr_2d_2[i]=i

In [47]:
arr_2d_2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])